routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     if(\Auth::user())
//     {
//         return  redirect('home');
//     } else{
        
//         return view('welcome');
//     }
// })->name('welcome');

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/validation', 'HomeController@validation')->name('validation');
Route::post('/dossiervalide', 'HomeController@dossiervalide')->name('dossiervalide');
Route::get('/export', 'HomeController@export')->name('export');
Route::post('/pdf', 'HomeController@pdf')->name('pdf');
Route::post('/api/villes', 'HomeController@villes')->name('villes');
Route::post('/dossier', 'HomeController@dossier')->name('dossier');

Route::resource('diploma','DiplomaController');
Route::resource('information','PersonalInformationController');
Route::resource('contact','PersonalInformationController');
Route::resource('cv','CurriculumVitaeController');
Route::resource('prerequisite','PrerequisiteController');

resources/views/admin.blade.php
@extends('layouts.dashboard')

@section('title', 'ESTO | Ecole Supérieure de Technologie - Oujda')

@section('breadcrumb', 'Dashboard')

@push('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('content')
<!-- Info boxes -->
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">DUT</span>
            <span class="info-box-number">{{ $total_dut }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">DEUP</span>
            <span class="info-box-number">{{ $total_deup }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-green"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">Autre</span>
            <span class="info-box-number">{{ $total_autre }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">candidats</span>
            <span class="info-box-number">{{ $total_members }}</span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->


<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Tous les candidats
          <a href="{{ route('export') }}" class="btn btn-xs btn-success">
            Exporter
          </a>
        </h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example3" class="table table-bordered table-hover">
          <thead>
          <tr>
            <th>#Numéro</th>
            <th>Nom et Prénom</th>
            <th>E-mail</th>
            <th>Date d'inscription</th>
            <th>Etat</th>
          </tr>
          </thead>
          <tbody>
          @foreach($users->unique('id') as $user)
          <tr>
            <td>{{ $user->id}} </td>
            <td>{{ title_case($user->name) }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->created_at }}</td>
            <td>
                @if ($user->is_valid == 1)
                <i class="fa fa-check text-success"></i> 
                @else
                  <i class="fa fa-close text-danger"></i> 
                @endif
            </td>
          </tr>
          @endforeach
          </tbody>
          <!-- <tfoot>
          <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Date de naissance</th>
            <th>Téléphone</th>
          </tr>
          </tfoot> -->
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->
@endsection

@push('scripts')
<!-- DataTables -->
<script src="{{ asset('components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script>
  $(function () {
    $('#example3').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false,
      "columnDefs": [
                    { "targets": [3,4], "searchable": false }
                ]
    });
  });  
</script>
@endpush

resources/views/chef.blade.php
@extends('layouts.dashboard')

@section('title', 'ESTO | Ecole Supérieure de Technologie - Oujda')

@section('breadcrumb', 'Dashboard')

@push('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush
@section('content')
<!-- Info boxes -->
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">DUT</span>
            <span class="info-box-number">{{ $total_dut }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">DEUP</span>
            <span class="info-box-number">{{ $total_deup }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-green"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">Autre</span>
            <span class="info-box-number">{{ $total_autre }}<!--<small>%</small>--></span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">candidats</span>
            <span class="info-box-number">{{ $total_members }}</span>
        </div>
        <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->


<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Tous les candidats
          <a href="{{ route('export') }}" class="btn btn-xs btn-success">
            Exporter
          </a>
        </h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
          <thead>
          <tr>
            <th>#Numéro</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Date de naissance</th>
            <th>Téléphone</th>
          </tr>
          </thead>
          <tbody>
          @foreach($users->unique('user_id') as $user)
          <tr>
            <td>{{ $user->user_id}} </td>
            <td>{{ title_case($user->family_name) }}</td>
            <td>{{ title_case($user->first_name) }}</td>
            <td>{{ $user->birth_date }}</td>
            <td>{{ $user->phone }}</td>
          </tr>
          @endforeach
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

<div class="row">
  <div class="col-md-8">
    <!-- TABLE: LATEST ORDERS -->
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Statistique</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <div class="table-responsive">
          
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <div class="col-md-4">
    <div class="box box-default">
      <div class="box-header with-border">
        <h3 class="box-title">% des candidats par type</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <div class="row">
          <div class="col-md-8">
            <div class="chart-responsive">
              <canvas id="pieChart" height="150"></canvas>
            </div>
            <!-- ./chart-responsive -->
          </div>
          <!-- /.col -->
          <div class="col-md-4">
            <ul class="chart-legend clearfix">
              <li><i class="fa fa-circle-o text-red"></i> DUT</li>
              <li><i class="fa fa-circle-o text-green"></i> DEUP</li>
              <li><i class="fa fa-circle-o text-yellow"></i> AUTRE</li>
            </ul>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.box-body -->
      <div class="box-footer no-padding">
        <ul class="nav nav-pills nav-stacked">
          @if ($total_members == 0)
          <li>
            <a href="#">DUT
              <span class="pull-right text-red"> 0%</span>
            </a>
          </li>
          <li>
            <a href="#">DEUP
              <span class="pull-right text-green"> 0%</span>
            </a>
          </li>
          <li>
            <a href="#">AUTRE
              <span class="pull-right text-yellow"> 0%</span>
            </a>
          </li>
          @else

          <li>
            <a href="#">DUT
              <span class="pull-right text-red"> {{ ($total_dut/$total_members)*100 }}%</span>
            </a>
          </li>
          <li>
            <a href="#">DEUP
              <span class="pull-right text-green"> {{ ($total_deup/$total_members)*100 }}%</span>
            </a>
          </li>
          <li>
            <a href="#">AUTRE
              <span class="pull-right text-yellow"> {{ ($total_autre/$total_members)*100 }}%</span>
            </a>
          </li>

          @endif
        </ul>
      </div>
      <!-- /.footer -->
    </div>
    <!-- /.box -->
  </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<!-- DataTables -->
<script src="{{ asset('components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('components/chart.js/Chart.js') }}"></script>
<script>
  $(function () {
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    });



      // -------------
  // - PIE CHART -
  // -------------
  // Get context with jQuery - using jQuery's .get() method.
  var pieChartCanvas = $('#pieChart').get(0).getContext('2d');
  var pieChart       = new Chart(pieChartCanvas);
  var PieData        = [
    {
      value    : {{ $total_dut }},
      color    : '#f56954',
      highlight: '#f56954',
      label    : 'DUT'
    },
    {
      value    : {{ $total_deup }},
      color    : '#00a65a',
      highlight: '#00a65a',
      label    : 'DEUP'
    },
    {
      value    : {{ $total_autre }},
      color    : '#f39c12',
      highlight: '#f39c12',
      label    : 'AUTRE'
    }
  ];
  var pieOptions     = {
    // Boolean - Whether we should show a stroke on each segment
    segmentShowStroke    : true,
    // String - The colour of each segment stroke
    segmentStrokeColor   : '#fff',
    // Number - The width of each segment stroke
    segmentStrokeWidth   : 1,
    // Number - The percentage of the chart that we cut out of the middle
    percentageInnerCutout: 50, // This is 0 for Pie charts
    // Number - Amount of animation steps
    animationSteps       : 100,
    // String - Animation easing effect
    animationEasing      : 'easeOutBounce',
    // Boolean - Whether we animate the rotation of the Doughnut
    animateRotate        : true,
    // Boolean - Whether we animate scaling the Doughnut from the centre
    animateScale         : false,
    // Boolean - whether to make the chart responsive to window resizing
    responsive           : true,
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio  : false,
    // String - A legend template
    legendTemplate       : '<ul class=\'<%=name.toLowerCase()%>-legend\'><% for (var i=0; i<segments.length; i++){%><li><span style=\'background-color:<%=segments[i].fillColor%>\'></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>',
    // String - A tooltip template
    tooltipTemplate      : '<%=value %> <%=label%>'
  };
  // Create pie or douhnut chart
  // You can switch between pie and douhnut using the method below.
  pieChart.Doughnut(PieData, pieOptions);
  // -----------------
  // - END PIE CHART -
  // -----------------

  });
</script>
@endpush

resources/views/export.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>la liste des candidats</title>
    <link href="{{ asset('js/dt/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('js/dt/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('js/dt/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <style>
        body {
            padding-top:100px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <table id="example" class="table table-striped table-bordered table-hover recu-dataTables">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Date de naissance</th>
                                <th>CNE</th>
                                <th>Série du Bac</th>
                                <th>Année de Bac</th>
                                <th>Moyenne du Bac</th>
                                <th>Type de diplôme Bac+2</th>
                                <th>Spécialité du diplôme Bac+2</th>

                                <th>Année d'inscription</th>
                                <th>Année d'obtention</th>
                                <th>Moyenne de la 1<sup>ère</sup> année</th>
                                <th>Moyenne de la 2<sup>éme</sup> année</th>
                                <th>le nombre d'année sans activité</th>
                                <th>Total des Prérequis</th>
                                <th>Email</th>
                                <th>Téléphone</th>
                                <th>CIN</th>
                                <th>Ville</th>
                                <th>Adresse</th>
                                <th>Zip Code</th>
                                <th>Genre</th> <th>Photo</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($users_diplome->unique('user_id') as $user)
                            <tr>
                                <td>{{ $user->user_id}} </td>
                                <td>{{ title_case($user->family_name) }}</td>
                                <td>{{ title_case($user->first_name) }}</td>
                                <td>{{ $user->birth_date }}</td>
                               @foreach($users_bac->unique('user_id') as $user_bac)
                                    @if($user->user_id == $user_bac->user_id)
                                    <td>{{ $user_bac->cne }}</td>
                                    <td>{{ $user_bac->entitled }}</td>
                                    <td>{{ $user_bac->year_of_graduation }}
                                    <td>{{ $user_bac->average }}</td>
</td>
                                    @endif
                                @endforeach
                                <td>{{ $user->type }} </td>
                                <td>{{ $user->entitled }} </td>

                                <td>{{ $user->year_of_registration }} </td>
                                <td>{{ $user->year_of_graduation }} </td>
                                <td>{{ $user->first_average }} </td>
                                <td>{{ $user->second_average }} </td>
                                <td>{{ $user->number_year_stop }} </td>
                                <td>
                                    <script>
                                        
                                        document.write(("{{ $user->prerequisites_list }}".match(/,/g) || []).length + 1);
                                    </script>
                                </td>
                                <td>{{ $user->email }}</td>

                                <td>{{ $user->phone }}</td>
                                 <td>{{ $user->id_number }}</td>
                                <td>{{ $user->city }}</td>
                                <td>{{ $user->address }}</td>
                                <td>{{ $user->zip_code }}</td>
                                <td>{{ $user->gender }}</td>
                                <td><img src="uploads/images/{{ $user->image }}" width='100px' height='100px'></td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ asset('js/dt/js/jquery-1.12.4.js') }}"></script>
<script src="{{ asset('js/dt/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/dt/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('js/dt/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('js/dt/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('js/dt/js/jszip.min.js') }}"></script>
<script src="{{ asset('js/dt/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('js/dt/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('js/dt/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('js/dt/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('js/dt/js/buttons.colVis.min.js') }}"></script>


<script>
    $(document).ready(function() {

        $(document).ready(function() {
            var table = $('#example').DataTable( {
                lengthChange: false,
                buttons: [ 'copy', 'excel', 'pdf','print' ],
                "columnDefs": [
                    { "targets": [4,5,6,7,8,9,10,11], "searchable": false }
                ]
            } );

            table.buttons().container().appendTo( '#example_wrapper .col-sm-6:eq(0)' );
        } );
    });
</script> 
</body>
</html>

resources/views/home.blade.php
@extends('layouts.apply',['personalInformation'=>$personalInformation])

@section('title', 'ESTO | Ecole Supérieure de Technologie - Oujda')

@section('breadcrumb', 'Mon dossier')

@push('styles')
  <style>
    label {
      font-weight: 400 !important;
    }
  </style>
@endpush
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Mon dossier</h3>
      </div>
      <!-- /.box-header -->
        <div class="box-body">
          <div class="box-group" id="accordion">
            <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
            <div class="panel box box-primary">
              <div class="box-header with-border">
                <h4 class="box-title">
                  @if($personalInformation)
                    <a href="{{ route('information.index') }}">
                      Mes Informations Personnelles #1 
                      <small class="text-green">complet</small>
                    </a>
                  @else
                    <a href="{{ route('information.index') }}">
                      Mes Informations Personnelles #1
                      <small class="text-red">Incomplet</small> 
                    </a>
                  @endif
                </h4>
              </div>
            </div>
            <div class="panel box box-danger">
              <div class="box-header with-border">
                <h4 class="box-title">
                  <a href="{{ route('diploma.index') }}">
                    Mon parcours et mes diplômes #2 
                    @if($diploma < 2 or $cv == 0 )
                      <small class="text-red">Incomplet</small>
                    @else
                      <small class="text-green">complet</small>
                    @endif
                  </a>
                </h4>
              </div>
            </div>
            <div class="panel box box-success">
              <div class="box-header with-border">
                <h4 class="box-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    Prérequis & Validation #3
                    @if($prerequisites )
                      <small class="text-green">complet</small>
                    @else
                      <small class="text-red">Incomplet</small>
                    @endif
                  </a>
                </h4>
              </div>
              <div id="collapseThree" class="panel-collapse collapse in">
                <div class="box-body">
                  <div class="col-md-6">
                      @foreach ($prerequis as $item)
                        <input @if(in_array($item, $prerequisites)) checked @endif id="item{{ $loop->index }}" type="checkbox" value="{{ $item }}" name="prerequisites_list[]"> <label for="item{{ $loop->index }}">{{ $item }}</label> <br>
                      @endforeach
                  </div>
                  <div class="col-md-6">
                    <p style="font-weight:bold;" class="text-danger">Attention, après la soumission de votre dossier, vous ne pourrez plus le modifier !</p>
                    <form role="form" action="{{ route('dossier') }}" method="post">
                      @csrf
                      <!-- <p>
                        <input name="certify" id="certify" type="checkbox">
                        <label style="display:inline;" for="certify">J'ai bien relu mon dossier et je certifie l'exactitude des informations qu'il contient</label>
                      </p>   -->
                      <button style="display:none;" id="prerequisite" type="button" class="btn btn-primary">Enregistrer</button>

                      <button id="prerequisite_disabled" type="button" class="btn btn-primary disabled">Enregistrer</button>

                      <button id="certify-btn" type="button" class="btn btn-danger disabled">Je soumets mon dossier</button>
                      @php
                        $dossier_pas_complet = true
                      @endphp
                      @if($prerequisites)
                        @if($personalInformation)
                          @if($diploma >= 2 and $cv != 0)
                            @php
                              $dossier_pas_complet = false
                            @endphp
                          @endif
                        @endif
                      @endif

                      @if($dossier_pas_complet)
                        <p class="help-block text-danger">
                          Votre dossier n'est pas complet. Vous ne pouvez pas le soumettre.
                        </p>
                      @endif
        
                    </form>  
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
  <div class="col-md-12">
    
  </div>
</div>
@endsection

@push('scripts')
<!-- InputMask -->
<script src="{{ asset('js/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('js/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('js/input-mask/jquery.inputmask.extensions.js') }}"></script>

<script src="{{ asset('js/intl-tel-input/js/intlTelInput.js') }}"></script>
<script>
  $("#phone").intlTelInput();
</script>
<script>
  $(function() {
    //Datemask dd/mm/yyyy
    $('#datemask, #datemask1').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
  });
</script>
<script>
    $(function(){



        $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });

        @if($prerequisites)
          @if($personalInformation)
            @if($diploma >= 2 and $cv != 0)
              //$('#certify').change(function(){
                  //if($('#certify').is(':checked') == true){
                      $('#certify-btn').removeClass('disabled');
                      $('#certify-btn').attr('type','submit');
                      $('#certify-btn').attr('onclick','return true;');
                  //}else{
                    //  $('#certify-btn').addClass('disabled');
                    //  $('#certify-btn').attr('onclick','return false;');
                  //}
              //});
            @endif
          @endif
        @endif

        $("input[name*='pre']").change(function(){
            $('#prerequisite_disabled').hide();
            $('#prerequisite').show();
        });

        $('#prerequisite').click(function(){
            //alert($("input[name*='prerequisites_list']"));

            var data = { 'prerequisites_list[]' : []};
            $("input[name*='pre']:checked").each(function() {
              data['prerequisites_list[]'].push($(this).val());
            });
            $.post("{{ route('prerequisite.store')}}", data,
            function(data){
                    window.location.reload();
            });
        });

    });
</script>
@endpush

resources/views/home_old.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection